# Generated by Django 3.1 on 2020-08-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_answer_question_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
