# Generated by Django 3.1 on 2020-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200813_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerContent', models.CharField(max_length=1024)),
                ('answerPeople', models.CharField(max_length=32)),
                ('answerTime', models.DateTimeField()),
                ('answerCollection', models.IntegerField()),
                ('approvalNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner', models.TextField(max_length=32)),
                ('questionName', models.CharField(max_length=64)),
                ('questionTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewPeople', models.CharField(max_length=32)),
            ],
        ),
    ]
