# Generated by Django 3.1 on 2020-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_answer_question_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewPeople', models.CharField(max_length=32)),
                ('reviewTime', models.DateTimeField()),
            ],
        ),
    ]
