# Generated by Django 3.1 on 2020-08-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.question'),
        ),
        migrations.AddField(
            model_name='reviewtable',
            name='answerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.answer'),
        ),
    ]
